import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-between p-5">
          <div id="logo"><img src="/logos/logo2.png" alt="Foto Logo" /></div>
          <div id="busca"> <input type="text" className="bg-gray-100 w-2xs" placeholder="Pesquisar"/> </div>
          <div id="login">  <button className="bg-gray-400 p-2 rounded-2xl">Login</button> </div>
            
        </header>
        <nav className="bg-black p-2">
          <ul className="flex justify-around">
            <li className="text-amber-50">Home</li> 
            <li className="text-amber-50">Sobre</li> 
            <li className="text-amber-50">Produtos</li> 
            <li className="text-amber-50">Contato</li> 
            
          </ul>
        </nav>
        {children}
        <footer className="bg-black p-2"> <p className="text-center text-amber-50">  Dev by @Thiago Almeida </p> </footer>
      </body>
    </html>
  );
}
